// Generated from RSSSF's English Football League final-table archive.
// Seasons are keyed by their ending year.

const ENGLISH_FIRST_DIVISION_TABLES = {
    "1966": [
        "Liverpool",
        "Leeds United",
        "Burnley",
        "Manchester United",
        "Chelsea",
        "West Bromwich Albion",
        "Leicester City",
        "Tottenham Hotspur",
        "Sheffield United",
        "Stoke City",
        "Everton",
        "West Ham United",
        "Blackpool",
        "Arsenal",
        "Newcastle United",
        "Aston Villa",
        "Sheffield Wednesday",
        "Nottingham Forest",
        "Sunderland",
        "Fulham",
        "Northampton",
        "Blackburn Rovers"
    ],
    "1967": [
        "Manchester United",
        "Nottingham Forest",
        "Tottenham Hotspur",
        "Leeds United",
        "Liverpool",
        "Everton",
        "Arsenal",
        "Leicester City",
        "Chelsea",
        "Sheffield United",
        "Sheffield Wednesday",
        "Stoke City",
        "West Bromwich Albion",
        "Burnley",
        "Manchester City",
        "West Ham United",
        "Sunderland",
        "Fulham",
        "Southampton",
        "Newcastle United",
        "Aston Villa",
        "Blackpool"
    ],
    "1968": [
        "Manchester City",
        "Manchester United",
        "Liverpool",
        "Leeds United",
        "Everton",
        "Chelsea",
        "Tottenham Hotspur",
        "West Bromwich Albion",
        "Arsenal",
        "Newcastle United",
        "Nottingham Forest",
        "West Ham United",
        "Leicester City",
        "Burnley",
        "Sunderland",
        "Southampton",
        "Wolverhampton Wanderers",
        "Stoke City",
        "Sheffield Wednesday",
        "Coventry City",
        "Sheffield United",
        "Fulham"
    ],
    "1969": [
        "Leeds United",
        "Liverpool",
        "Everton",
        "Arsenal",
        "Chelsea",
        "Tottenham Hotspur",
        "Southampton",
        "West Ham United",
        "Newcastle United",
        "West Bromwich Albion",
        "Manchester United",
        "Ipswich Town",
        "Manchester City",
        "Burnley",
        "Sheffield Wednesday",
        "Wolverhampton Wanderers",
        "Sunderland",
        "Nottingham Forest",
        "Stoke City",
        "Coventry City",
        "Leicester City",
        "Queen'S Park Rangers"
    ],
    "1970": [
        "Everton",
        "Leeds United",
        "Chelsea",
        "Derby County",
        "Liverpool",
        "Coventry City",
        "Newcastle United",
        "Manchester United",
        "Stoke City",
        "Manchester City",
        "Tottenham Hotspur",
        "Arsenal",
        "Wolverhampton Wanderers",
        "Burnley",
        "Nottingham Forest",
        "West Bromwich Albion",
        "West Ham United",
        "Ipswich Town",
        "Southampton",
        "Crystal Palace",
        "Sunderland",
        "Sheffield Wednesday"
    ],
    "1971": [
        "Arsenal",
        "Leeds United",
        "Tottenham Hotspur",
        "Wolverhampton Wanderers",
        "Liverpool",
        "Chelsea",
        "Southampton",
        "Manchester United",
        "Derby County",
        "Coventry City",
        "Manchester City",
        "Newcastle United",
        "Stoke City",
        "Everton",
        "Huddersfield Town",
        "Nottingham Forest",
        "West Bromwich Albion",
        "Crystal Palace",
        "Ipswich Town",
        "West Ham United",
        "Burnley",
        "Blackpool"
    ],
    "1972": [
        "Derby County",
        "Leeds United",
        "Liverpool",
        "Manchester City",
        "Arsenal",
        "Tottenham Hotspur",
        "Chelsea",
        "Manchester United",
        "Wolverhampton Wanderers",
        "Sheffield United",
        "Newcastle United",
        "Leicester City",
        "Ipswich Town",
        "West Ham United",
        "Everton",
        "West Bromwich Albion",
        "Stoke City",
        "Coventry City",
        "Southampton",
        "Crystal Palace",
        "Nottingham Forest",
        "Huddersfield Town"
    ],
    "1973": [
        "Liverpool",
        "Arsenal",
        "Leeds United",
        "Ipswich Town",
        "Wolverhampton Wanderers",
        "West Ham United",
        "Derby County",
        "Tottenham Hotspur",
        "Newcastle United",
        "Birmingham City",
        "Manchester City",
        "Chelsea",
        "Southampton",
        "Sheffield United",
        "Stoke City",
        "Leicester City",
        "Everton",
        "Manchester United",
        "Coventry City",
        "Norwich City",
        "Crystal Palace",
        "West Bromwich Albion"
    ],
    "1974": [
        "Leeds United",
        "Liverpool",
        "Derby County",
        "Ipswich Town",
        "Stoke City",
        "Burnley",
        "Everton",
        "Queen'S Park Rangers",
        "Leicester City",
        "Arsenal",
        "Tottenham Hotspur",
        "Wolverhampton Wanderers",
        "Sheffield United",
        "Manchester City",
        "Newcastle United",
        "Coventry City",
        "Chelsea",
        "West Ham United",
        "Birmingham City",
        "Southampton",
        "Manchester United",
        "Norwich City"
    ],
    "1975": [
        "Derby County",
        "Liverpool",
        "Ipswich Town",
        "Everton",
        "Stoke City",
        "Sheffield United",
        "Middlesbrough",
        "Manchester City",
        "Leeds United",
        "Burnley",
        "Queen'S Park Rangers",
        "Wolverhampton Wanderers",
        "West Ham United",
        "Coventry City",
        "Newcastle United",
        "Arsenal",
        "Birmingham City",
        "Leicester City",
        "Tottenham Hotspur",
        "Luton Town",
        "Chelsea",
        "Carlisle United"
    ],
    "1976": [
        "Liverpool",
        "Queen'S Park Rangers",
        "Manchester United",
        "Derby County",
        "Leeds United",
        "Ipswich Town",
        "Leicester City",
        "Manchester City",
        "Tottenham Hotspur",
        "Norwich City",
        "Everton",
        "Stoke City",
        "Middlesbrough",
        "Coventry City",
        "Newcastle United",
        "Aston Villa",
        "Arsenal",
        "West Ham United",
        "Birmingham City",
        "Wolverhampton Wanderers",
        "Burnley",
        "Sheffield United"
    ],
    "1977": [
        "Liverpool",
        "Manchester City",
        "Ipswich Town",
        "Aston Villa",
        "Newcastle United",
        "Manchester United",
        "West Bromwich Albion",
        "Arsenal",
        "Everton",
        "Leeds United",
        "Leicester City",
        "Middlesbrough",
        "Birmingham City",
        "Queen'S Park Rangers",
        "Derby County",
        "Norwich City",
        "West Ham United",
        "Bristol City",
        "Coventry City",
        "Sunderland",
        "Stoke City",
        "Tottenham Hotspur"
    ],
    "1978": [
        "Nottingham Forest",
        "Liverpool",
        "Everton",
        "Manchester City",
        "Arsenal",
        "West Bromwich Albion",
        "Coventry City",
        "Aston Villa",
        "Leeds United",
        "Manchester United",
        "Birmingham City",
        "Derby County",
        "Norwich City",
        "Middlesbrough",
        "Wolverhampton Wanderers",
        "Chelsea",
        "Bristol City",
        "Ipswich Town",
        "Queens Park Rangers",
        "West Ham United",
        "Newcastle United",
        "Leicester City"
    ],
    "1979": [
        "Liverpool",
        "Nottingham Forest",
        "West Bromwich Albion",
        "Everton",
        "Leeds United",
        "Ipswich Town",
        "Arsenal",
        "Aston Villa",
        "Manchester United",
        "Coventry City",
        "Tottenham Hotspur",
        "Middlesbrough",
        "Bristol City",
        "Southampton",
        "Manchester City",
        "Norwich City",
        "Bolton Wanderers",
        "Wolverhampton Wanderers",
        "Derby County",
        "Queens Park Rangers",
        "Birmingham City",
        "Chelsea"
    ],
    "1980": [
        "Liverpool",
        "Manchester United",
        "Ipswich Town",
        "Arsenal",
        "Nottingham Forest",
        "Wolverhampton Wanderers",
        "Aston Villa",
        "Southampton",
        "Middlesbrough",
        "West Bromwich Albion",
        "Leeds United",
        "Norwich City",
        "Crystal Palace",
        "Tottenham Hotspur",
        "Coventry City",
        "Brighton & Hove Albion",
        "Manchester City",
        "Stoke City",
        "Everton",
        "Bristol City",
        "Derby County",
        "Bolton Wanderers"
    ],
    "1981": [
        "Aston Villa",
        "Ipswich Town",
        "Arsenal",
        "West Bromwich Albion",
        "Liverpool",
        "Southampton",
        "Nottingham Forest",
        "Manchester United",
        "Leeds United",
        "Tottenham Hotspur",
        "Stoke City",
        "Manchester City",
        "Birmingham City",
        "Middlesbrough",
        "Everton",
        "Coventry City",
        "Sunderland",
        "Wolverhampton Wanderers",
        "Brighton & Hove Albion",
        "Norwich City",
        "Leicester City",
        "Crystal Palace"
    ],
    "1982": [
        "Liverpool",
        "Ipswich Town",
        "Manchester United",
        "Tottenham Hotspur",
        "Arsenal",
        "Swansea City",
        "Southampton",
        "Everton",
        "West Ham United",
        "Manchester City",
        "Aston Villa",
        "Nottingham Forest",
        "Brighton & Hove Albion",
        "Coventry City",
        "Notts County",
        "Birmingham City",
        "West Bromwich Albion",
        "Stoke City",
        "Sunderland",
        "Leeds United",
        "Wolverhampton Wanderers",
        "Middlesbrough"
    ],
    "1983": [
        "Liverpool",
        "Watford",
        "Manchester United",
        "Tottenham Hotspur",
        "Nottingham Forest",
        "Aston Villa",
        "Everton",
        "West Ham United",
        "Ipswich Town",
        "Arsenal",
        "West Bromwich Albion",
        "Southampton",
        "Stoke City",
        "Norwich City",
        "Notts County",
        "Sunderland",
        "Birmingham City",
        "Luton Town",
        "Coventry City",
        "Manchester City",
        "Swansea City",
        "Brighton & Hove Albion"
    ],
    "1984": [
        "Liverpool",
        "Southampton",
        "Nottingham Forest",
        "Manchester United",
        "Queen'S Park Rangers",
        "Arsenal",
        "Everton",
        "Tottenham Hotspur",
        "West Ham United",
        "Aston Villa",
        "Watford",
        "Ipswich Town",
        "Sunderland",
        "Norwich City",
        "Leicester City",
        "Luton Town",
        "West Bromwich Albion",
        "Stoke City",
        "Coventry City",
        "Birmingham City",
        "Notts County",
        "Wolverhampton Wanderers"
    ],
    "1985": [
        "Everton",
        "Liverpool",
        "Tottenham Hotspur",
        "Manchester United",
        "Southampton",
        "Chelsea",
        "Arsenal",
        "Sheffield Wednesday",
        "Nottingham Forest",
        "Aston Villa",
        "Watford",
        "West Bromwich Albion",
        "Luton Town",
        "Newcastle United",
        "Leicester City",
        "West Ham United",
        "Ipswich Town",
        "Coventry City",
        "Queens Park Rangers",
        "Norwich City",
        "Sunderland",
        "Stoke City"
    ],
    "1986": [
        "Liverpool",
        "Everton",
        "West Ham United",
        "Manchester United",
        "Sheffield Wednesday",
        "Chelsea",
        "Arsenal",
        "Nottingham Forest",
        "Luton Town",
        "Tottenham Hotspur",
        "Newcastle United",
        "Watford",
        "Queen'S Park Rangers",
        "Southampton",
        "Manchester City",
        "Aston Villa",
        "Coventry City",
        "Oxford United",
        "Leicester City",
        "Ipswich Town",
        "Birmingham City",
        "West Bromwich Albion"
    ],
    "1987": [
        "Everton",
        "Liverpool",
        "Tottenham Hotspur",
        "Arsenal",
        "Norwich City",
        "Wimbledon",
        "Luton Town",
        "Nottingham Forest",
        "Watford",
        "Coventry City",
        "Manchester United",
        "Southampton",
        "Sheffield Wednesday",
        "Chelsea",
        "West Ham United",
        "Queen'S Park Rangers",
        "Newcastle United",
        "Oxford United",
        "Charlton Athletic",
        "Leicester City",
        "Manchester City",
        "Aston Villa"
    ],
    "1988": [
        "Liverpool",
        "Manchester United",
        "Nottingham Forest",
        "Everton",
        "Queen'S Park Rangers",
        "Arsenal",
        "Wimbledon",
        "Newcastle United",
        "Luton Town",
        "Coventry City",
        "Sheffield Wednesday",
        "Southampton",
        "Tottenham Hotspur",
        "Norwich City",
        "Derby County",
        "West Ham United",
        "Charlton Athletic",
        "Chelsea",
        "Portsmouth",
        "Watford",
        "Oxford United"
    ],
    "1989": [
        "Arsenal",
        "Liverpool",
        "Nottingham Forest",
        "Norwich City",
        "Derby County",
        "Tottenham Hotspur",
        "Coventry City",
        "Everton",
        "Queen'S Park Rangers",
        "Millwall",
        "Manchester United",
        "Wimbledon",
        "Southampton",
        "Charlton Athletic",
        "Sheffield Wednesday",
        "Luton Town",
        "Aston Villa",
        "Middlesbrough",
        "West Ham United",
        "Newcastle United"
    ],
    "1990": [
        "Liverpool",
        "Aston Villa",
        "Tottenham Hotspur",
        "Arsenal",
        "Chelsea",
        "Everton",
        "Southampton",
        "Wimbledon",
        "Nottingham Forest",
        "Norwich City",
        "Queen'S Park Rangers",
        "Coventry City",
        "Manchester United",
        "Manchester City",
        "Crystal Palace",
        "Derby County",
        "Luton Town",
        "Sheffield Wednesday",
        "Charlton Athletic",
        "Millwall"
    ],
    "1991": [
        "Arsenal",
        "Liverpool",
        "Crystal Palace",
        "Leeds United",
        "Manchester City",
        "Manchester United",
        "Wimbledon",
        "Nottingham Forest",
        "Everton",
        "Tottenham Hotspur",
        "Chelsea",
        "Queen'S Park Rangers",
        "Sheffield United",
        "Southampton",
        "Norwich City",
        "Coventry City",
        "Aston Villa",
        "Luton Town",
        "Sunderland",
        "Derby County"
    ],
    "1992": [
        "Leeds United",
        "Manchester United",
        "Sheffield Wednesday",
        "Arsenal",
        "Manchester City",
        "Liverpool",
        "Aston Villa",
        "Nottingham Forest",
        "Sheffield United",
        "Crystal Palace",
        "Queen'S Park Rangers",
        "Everton",
        "Wimbledon",
        "Chelsea",
        "Tottenham Hotspur",
        "Southampton",
        "Oldham Athletic",
        "Norwich City",
        "Coventry City",
        "Luton Town",
        "Notts County",
        "West Ham United"
    ]
};

module.exports = { ENGLISH_FIRST_DIVISION_TABLES };
